name: Enforce Branch Naming

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Branch Name
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          echo "Branch name is: $BRANCH_NAME"

          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|release)\/[a-z0-9._-]+$ ]]; then
            echo "❌ Invalid branch name: $BRANCH_NAME"
            echo "Branch names must follow pattern: feature/xxx, bugfix/xxx, etc."
            exit 1
          else
            echo "✅ Valid branch name"
          fi
