name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21.7.1

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test


  build_android:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21.7.1

      - name: Install Dependencies
        run: npm install

      - name: Bundle Android App
        run: |
          mkdir -p android/app/build/intermediates/assets/release/
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/build/intermediates/assets/release/index.android.bundle \
            --assets-dest android/app/build/intermediates/res/merged/release

      - name: Build Android Release
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew bundleRelease -Pkeystore.password=${{ secrets.KEYSTORE_PASSWORD }}

  download_bundle:
    runs-on: ubuntu-latest
    needs: build_android

    steps:
      - name: Archive Android Bundle
        uses: actions/upload-artifact@v4
        with:
          name: android-bundle
          path: android/app/build/outputs/bundle/release/app-release.aab
